import mongoose from 'mongoose';
import { Priority } from '../constants/task.constants';

/**
 * Interface representing a task document in the database.
 * Provides a structured representation of task data.
 */
export interface Task extends mongoose.Document {
  /**
   * The unique identifier of the task.
   * Auto-generated by MongoDB.
   */
  _id?: mongoose.Schema.Types.ObjectId;

  /**
   * The title of the task.
   * Should be concise and descriptive.
   */
  title: string;

  /**
   * The description of the task.
   * Provides additional details about the task.
   */
  description: string;

  /**
   * The due date of the task.
   * Specifies the deadline for completing the task.
   */
  dueDate: Date;

  /**
   * The deadline of the task.
   * Represents the final date by which the task must be completed.
   */
  deadLine: string;

  /**
   * The priority of the task.
   * Indicates the importance or urgency of the task.
   */
  priority: Priority;

  /**
   * Indicates whether the task is completed.
   * Helps track the status of the task.
   */
  completed: boolean;

  /**
   * The ID of the user associated with the task.
   * Represents the owner or assignee of the task.
   */
  user: mongoose.Schema.Types.ObjectId;

  /**
   * The IDs of labels associated with the task.
   * Categorizes or tags the task for organization and filtering.
   */
  labels: [mongoose.Schema.Types.ObjectId];

  /**
   * The IDs of lists associated with the task.
   * Specifies the task lists or boards to which the task belongs.
   */
  lists: [mongoose.Schema.Types.ObjectId];

  /**
   * The timestamp of when the task was created.
   * Automatically recorded upon task creation.
   */
  createdAt?: Date;

  /**
   * The timestamp of when the task was last updated.
   * Automatically updated whenever the task details are modified.
   */
  updatedAT?: Date;
}
